# Generated by Django 6.0.6 on 2026-06-17 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Ícone')),
                ('category', models.CharField(choices=[('progress', 'Progresso'), ('streak', 'Sequência'), ('financial', 'Financeiro'), ('social', 'Social'), ('special', 'Especial')], max_length=20, verbose_name='Categoria')),
                ('locked_by_default', models.BooleanField(default=True, verbose_name='Bloqueada por padrão')),
            ],
            options={
                'verbose_name': 'Conquista',
                'verbose_name_plural': 'Conquistas',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Ícone (emoji ou nome)')),
                ('order_index', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Idade')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Conteúdo / enunciado')),
                ('lesson_type', models.CharField(choices=[('quiz', 'Quiz'), ('challenge', 'Desafio'), ('content', 'Conteúdo')], default='content', max_length=20, verbose_name='Tipo')),
                ('order_index', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem dentro do módulo')),
                ('xp_reward', models.PositiveIntegerField(default=10, verbose_name='Recompensa XP')),
                ('coins_reward', models.PositiveIntegerField(default=5, verbose_name='Recompensa Moedas')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.module')),
            ],
            options={
                'verbose_name': 'Lição',
                'verbose_name_plural': 'Lições',
                'ordering': ['module', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='Nível')),
                ('xp_total', models.PositiveIntegerField(default=0, verbose_name='XP total')),
                ('xp_next_level', models.PositiveIntegerField(default=100, verbose_name='XP para próximo nível')),
                ('coins', models.PositiveIntegerField(default=0, verbose_name='Moedas')),
                ('streak_days', models.PositiveIntegerField(default=0, verbose_name='Streak (dias)')),
                ('last_activity', models.DateField(blank=True, null=True, verbose_name='Última atividade')),
                ('avatar', models.CharField(default='pessoa1', max_length=20, verbose_name='Avatar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.PositiveIntegerField(verbose_name='Moedas no período')),
                ('rank', models.PositiveIntegerField(verbose_name='Posição')),
                ('scope', models.CharField(choices=[('global', 'Global'), ('friends', 'Amigos'), ('school', 'Escola')], default='global', max_length=20, verbose_name='Escopo')),
                ('period', models.DateField(verbose_name='Período (início da semana)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrada no ranking',
                'verbose_name_plural': 'Entradas no ranking',
                'ordering': ['scope', 'period', 'rank'],
                'unique_together': {('user', 'scope', 'period')},
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='Conquistada em')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_by', to='core.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conquista do usuário',
                'verbose_name_plural': 'Conquistas dos usuários',
                'unique_together': {('user', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='UserLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, verbose_name='Concluída')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='Pontuação (0-100)')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluída em')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='core.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progresso na lição',
                'verbose_name_plural': 'Progressos nas lições',
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
