# Generated by Django 6.0.6 on 2026-06-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default='1990-01-01', verbose_name='Data de Nascimento'),
            preserve_default=False,
        ),
    ]
