PLAY_QUESTIONS = [
    {
        "id": 1,
        "level": "base",
        "level_title": "Nivel Base",
        "topic": "Orcamento",
        "title": "Money Basics",
        "statement": "O orcamento pessoal e o ponto de partida do planejamento financeiro porque mostra para onde o dinheiro vai.",
        "answer": True,
        "explanation": "Controlar o orcamento ajuda a alocar recursos conscientemente para objetivos e e um dos comportamentos financeiros mais ligados ao bem-estar financeiro.",
        "xp": 10,
        "coins": 5,
    },
    {
        "id": 2,
        "level": "base",
        "level_title": "Nivel Base",
        "topic": "Poupanca",
        "title": "Saving",
        "statement": "Poupanca e investimento sao sinonimos e servem exatamente para a mesma finalidade.",
        "answer": False,
        "explanation": "Poupanca prioriza protecao e liquidez para curto prazo e emergencias. Investimento busca crescimento, aceita risco e costuma mirar medio e longo prazo.",
        "xp": 10,
        "coins": 5,
    },
    {
        "id": 3,
        "level": "base",
        "level_title": "Nivel Base",
        "topic": "Juros",
        "title": "Compound",
        "statement": "Nos juros compostos, os juros incidem sobre o saldo acumulado, nao apenas sobre o valor inicial.",
        "answer": True,
        "explanation": "Esse efeito faz o crescimento acelerar com o tempo. No curto prazo a diferenca parece pequena, mas no longo prazo ela se torna enorme.",
        "xp": 10,
        "coins": 5,
    },
    {
        "id": 4,
        "level": "base",
        "level_title": "Nivel Base",
        "topic": "Reserva",
        "title": "Emergency Fund",
        "statement": "Toda pessoa deve ter exatamente o mesmo tamanho de reserva de emergencia.",
        "answer": False,
        "explanation": "A reserva depende da estabilidade da renda. Emprego formal costuma pedir 3 a 6 meses; renda variavel, MEI e autonomos podem precisar de 6 a 12 meses.",
        "xp": 10,
        "coins": 5,
    },
    {
        "id": 5,
        "level": "base",
        "level_title": "Nivel Base",
        "topic": "Inflacao",
        "title": "Inflation",
        "statement": "Guardar dinheiro sem rendimento pode reduzir o poder de compra ao longo do tempo.",
        "answer": True,
        "explanation": "A inflacao faz o dinheiro comprar menos. Para preservar riqueza, o investimento precisa render acima da inflacao.",
        "xp": 10,
        "coins": 5,
    },
    {
        "id": 6,
        "level": "base",
        "level_title": "Nivel Base",
        "topic": "Credito",
        "title": "Credit Score",
        "statement": "Fazer muitas consultas de credito em curto prazo costuma melhorar o score.",
        "answer": False,
        "explanation": "Muitas consultas em pouco tempo podem sinalizar busca intensa por credito. Pagar em dia, manter cadastro positivo e construir historico ajudam mais.",
        "xp": 10,
        "coins": 5,
    },
    {
        "id": 7,
        "level": "base",
        "level_title": "Nivel Base",
        "topic": "Tesouro",
        "title": "Selic",
        "statement": "Tesouro Selic costuma ser indicado para reserva de emergencia por liquidez e baixo risco.",
        "answer": True,
        "explanation": "Ele acompanha a Selic, e pos-fixado e tem alta liquidez. IPCA+ e Prefixado tem perfis diferentes e oscilam mais.",
        "xp": 10,
        "coins": 5,
    },
    {
        "id": 8,
        "level": "base",
        "level_title": "Nivel Base",
        "topic": "Cartao",
        "title": "Debt Trap",
        "statement": "Pagar apenas o minimo da fatura e uma boa forma de ganhar tempo sem custo relevante.",
        "answer": False,
        "explanation": "O saldo restante entra no rotativo, que tem juros muito altos. A regra saudavel e pagar o total da fatura.",
        "xp": 10,
        "coins": 5,
    },
    {
        "id": 9,
        "level": "base",
        "level_title": "Nivel Base",
        "topic": "Diversificacao",
        "title": "Portfolio",
        "statement": "Combinar ativos com baixa correlacao pode reduzir o risco total da carteira.",
        "answer": True,
        "explanation": "A diversificacao reduz riscos especificos de empresas e setores, embora nao elimine o risco sistematico da economia.",
        "xp": 10,
        "coins": 5,
    },
    {
        "id": 10,
        "level": "base",
        "level_title": "Nivel Base",
        "topic": "Previdencia",
        "title": "Retirement",
        "statement": "INSS e previdencia privada funcionam pelo mesmo regime financeiro.",
        "answer": False,
        "explanation": "O INSS funciona por reparticao: trabalhadores ativos financiam aposentados atuais. Previdencia privada funciona por capitalizacao individual.",
        "xp": 10,
        "coins": 5,
    },
    {
        "id": 11,
        "level": "medio",
        "level_title": "Nivel Medio",
        "topic": "Renda Fixa",
        "title": "Tax Shield",
        "statement": "LCI e LCA sao isentas de imposto de renda para pessoa fisica.",
        "answer": True,
        "explanation": "LCI e LCA tem isencao para pessoa fisica. CDB e Tesouro Direto seguem tabela regressiva de IR.",
        "xp": 15,
        "coins": 7,
    },
    {
        "id": 12,
        "level": "medio",
        "level_title": "Nivel Medio",
        "topic": "CDI",
        "title": "Benchmark",
        "statement": "Um CDB a 80% do CDI geralmente tende a ser inferior ao Tesouro Selic apos considerar taxas e alternativas.",
        "answer": True,
        "explanation": "O CDI anda muito proximo da Selic. Produtos muito abaixo de 100% do CDI raramente compensam frente ao Tesouro Selic.",
        "xp": 15,
        "coins": 7,
    },
    {
        "id": 13,
        "level": "medio",
        "level_title": "Nivel Medio",
        "topic": "Acoes",
        "title": "Valuation",
        "statement": "P/L baixo sempre significa que a acao esta barata.",
        "answer": False,
        "explanation": "P/L baixo pode indicar empresa estagnada ou em declinio. O indicador deve ser comparado no setor e combinado com outras metricas.",
        "xp": 15,
        "coins": 7,
    },
    {
        "id": 14,
        "level": "medio",
        "level_title": "Nivel Medio",
        "topic": "FIIs",
        "title": "Income",
        "statement": "Fundos imobiliarios distribuem grande parte do lucro e podem gerar renda recorrente.",
        "answer": True,
        "explanation": "FIIs distribuem 95% do lucro. Os rendimentos podem ser isentos para pessoa fisica em condicoes padrao, mas ha riscos como vacancia e Selic.",
        "xp": 15,
        "coins": 7,
    },
    {
        "id": 15,
        "level": "medio",
        "level_title": "Nivel Medio",
        "topic": "Perfil",
        "title": "Suitability",
        "statement": "Um investidor arrojado deveria investir 100% em renda variavel.",
        "answer": False,
        "explanation": "Perfil arrojado nao elimina reserva de emergencia nem diversificacao. Horizonte, tolerancia a perda e objetivo tambem importam.",
        "xp": 15,
        "coins": 7,
    },
    {
        "id": 16,
        "level": "medio",
        "level_title": "Nivel Medio",
        "topic": "Aportes",
        "title": "DCA",
        "statement": "Investir um valor fixo periodicamente pode reduzir a necessidade de acertar o melhor momento do mercado.",
        "answer": True,
        "explanation": "O DCA compra mais cotas quando o preco cai e menos quando sobe, criando disciplina e diluindo o preco medio.",
        "xp": 15,
        "coins": 7,
    },
    {
        "id": 17,
        "level": "medio",
        "level_title": "Nivel Medio",
        "topic": "Liquidez",
        "title": "Liquidity",
        "statement": "Imoveis fisicos e acoes de grandes empresas tem liquidez parecida.",
        "answer": False,
        "explanation": "Acoes liquidas podem ser vendidas em segundos. Imoveis fisicos podem levar meses para vender sem perda relevante de valor.",
        "xp": 15,
        "coins": 7,
    },
    {
        "id": 18,
        "level": "medio",
        "level_title": "Nivel Medio",
        "topic": "ETFs",
        "title": "Indexing",
        "statement": "ETFs de indices amplos podem ser eficientes para quem nao tem tempo de analisar ativos individualmente.",
        "answer": True,
        "explanation": "ETFs costumam ter taxas baixas e muitos fundos ativos perdem para indices em janelas longas. Eles podem ser uma estrategia simples e diversificada.",
        "xp": 15,
        "coins": 7,
    },
    {
        "id": 19,
        "level": "medio",
        "level_title": "Nivel Medio",
        "topic": "Retorno Real",
        "title": "Fisher",
        "statement": "Retorno real sempre e igual ao retorno nominal menos a inflacao.",
        "answer": False,
        "explanation": "A aproximacao pode enganar. A formula correta e (1 + nominal) / (1 + inflacao) - 1.",
        "xp": 15,
        "coins": 7,
    },
    {
        "id": 20,
        "level": "medio",
        "level_title": "Nivel Medio",
        "topic": "Sucessao",
        "title": "VGBL",
        "statement": "VGBL pode facilitar planejamento sucessorio ao permitir beneficiarios indicados diretamente.",
        "answer": True,
        "explanation": "O VGBL pode nao entrar em inventario e permitir transferencia mais agil aos beneficiarios, conforme regras aplicaveis.",
        "xp": 15,
        "coins": 7,
    },
    {
        "id": 21,
        "level": "avancado",
        "level_title": "Nivel Avancado",
        "topic": "Duration",
        "title": "Rates",
        "statement": "Duration modificada mede a sensibilidade aproximada do preco de um titulo a mudancas na taxa de juros.",
        "answer": True,
        "explanation": "Uma duration modificada de 5 indica que alta de 1 ponto percentual nas taxas reduz o preco em aproximadamente 5%.",
        "xp": 20,
        "coins": 10,
    },
    {
        "id": 22,
        "level": "avancado",
        "level_title": "Nivel Avancado",
        "topic": "Comportamental",
        "title": "Bias",
        "statement": "Pessoas tendem a subestimar crescimento exponencial, inclusive em dividas e juros compostos.",
        "answer": True,
        "explanation": "Esse vies explica por que muita gente subestima o crescimento de dividas rotativas e tambem o potencial de acumulacao de riqueza.",
        "xp": 20,
        "coins": 10,
    },
    {
        "id": 23,
        "level": "avancado",
        "level_title": "Nivel Avancado",
        "topic": "Fronteira",
        "title": "Efficient",
        "statement": "A fronteira eficiente inclui qualquer carteira que tenha retorno positivo.",
        "answer": False,
        "explanation": "A fronteira eficiente inclui carteiras que maximizam retorno para cada nivel de risco, ou minimizam risco para um retorno esperado.",
        "xp": 20,
        "coins": 10,
    },
    {
        "id": 24,
        "level": "avancado",
        "level_title": "Nivel Avancado",
        "topic": "Politica Monetaria",
        "title": "Central Bank",
        "statement": "A politica monetaria atua por canais como credito, cambio, expectativas e riqueza.",
        "answer": True,
        "explanation": "No Brasil, expectativas tem peso importante. Como os efeitos da Selic demoram meses, o Banco Central age olhando projecoes.",
        "xp": 20,
        "coins": 10,
    },
    {
        "id": 25,
        "level": "avancado",
        "level_title": "Nivel Avancado",
        "topic": "Risco",
        "title": "Tail Risk",
        "statement": "Basel III adotou o VaR como medida central definitiva para risco de mercado.",
        "answer": False,
        "explanation": "Basel III migrou para Expected Shortfall, pois o VaR ignora perdas alem da cauda e pode subestimar eventos extremos.",
        "xp": 20,
        "coins": 10,
    },
    {
        "id": 26,
        "level": "avancado",
        "level_title": "Nivel Avancado",
        "topic": "Juros Longos",
        "title": "Yield Curve",
        "statement": "A inversao da curva de juros pode sinalizar expectativa de recessao ou mudancas fortes na taxa futura.",
        "answer": True,
        "explanation": "Nos EUA, o spread 2 anos/10 anos antecedeu varias recessoes. No Brasil tambem pode refletir risco fiscal ou expectativa de cortes da Selic.",
        "xp": 20,
        "coins": 10,
    },
    {
        "id": 27,
        "level": "avancado",
        "level_title": "Nivel Avancado",
        "topic": "PGBL",
        "title": "Tax Planning",
        "statement": "PGBL sempre e vantajoso, inclusive para quem faz declaracao simplificada.",
        "answer": False,
        "explanation": "PGBL deduz ate 12% da renda bruta tributavel apenas na declaracao completa. Para declaracao simplificada, VGBL costuma ser mais adequado.",
        "xp": 20,
        "coins": 10,
    },
    {
        "id": 28,
        "level": "avancado",
        "level_title": "Nivel Avancado",
        "topic": "Mercados",
        "title": "EMH",
        "statement": "A Hipotese dos Mercados Eficientes e consenso comprovado e nao tem evidencias contrarias.",
        "answer": False,
        "explanation": "Existem anomalias documentadas, momentum, premio de valor e bolhas. A eficiencia do mercado pode variar conforme contexto.",
        "xp": 20,
        "coins": 10,
    },
    {
        "id": 29,
        "level": "avancado",
        "level_title": "Nivel Avancado",
        "topic": "Alavancagem",
        "title": "Leverage",
        "statement": "Com alavancagem de 10 vezes, uma queda de 10% no ativo pode eliminar 100% do capital proprio.",
        "answer": True,
        "explanation": "A alavancagem amplia ganhos e perdas. Perdas grandes exigem retornos ainda maiores para recuperar o capital.",
        "xp": 20,
        "coins": 10,
    },
    {
        "id": 30,
        "level": "avancado",
        "level_title": "Nivel Avancado",
        "topic": "Corporate Finance",
        "title": "NPV",
        "statement": "O VPL e superior a TIR para comparar projetos mutuamente excludentes com escalas diferentes.",
        "answer": True,
        "explanation": "O VPL mostra a riqueza absoluta gerada. A TIR pode falhar com escalas diferentes, fluxos com trocas de sinal e pressupostos de reinvestimento.",
        "xp": 20,
        "coins": 10,
    },
]

